name: ResNet56_CIFAR100_clean
n_gpu: 1
model:
  type: ResNet56
  args: 
    deg_flag: clean
    num_class: 100
data_loader:
  type: DegCIFAR100DataLoader
  args:
    data_dir: data/
    batch_size: 128
    shuffle: true
    validation_split: 0.0
    num_workers: 3
    deg_type: jpeg
    cutout_method: Cutout
    cutout_length: 16
    cutout_apply_clean: True
optimizer:
  type: SGD
  args:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0005
loss: 
  - supervised_loss: CE
loss_weights: [1.0]
metrics:
- accuracy
lr_scheduler:
  type: MultiStepLR
  args:
    milestones: [60, 120, 160]
    gamma: 0.2
trainer:
  type: IndTrainer
  args:
    epochs: 200
    save_dir: saved/
    save_period: 1
    verbosity: 2
    monitor: max val_accuracy_clean
    early_stop: 200
    tensorboard: true