name: ResNet56_CIFAR10_deg_scratch
n_gpu: 1
model:
  type: ResNet56
  args: 
    deg_flag: deg
    num_class: 10
data_loader:
  type: DegCIFAR10DataLoader
  args:
    data_dir: data/
    batch_size: 128
    shuffle: true
    validation_split: 0.0
    num_workers: 2
    deg_type: jpeg
    cutout_apply_clean: true
    cutout_apply_deg: true
    cutout_method: Cutout
    cutout_length: 16
optimizer:
  type: SGD
  args:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0001
loss: 
  - supervised_loss: CE
loss_weights: [1.0]
metrics:
- accuracy
lr_scheduler:
  type: MultiStepLR
  args:
    milestones: [60, 140, 180]
    gamma: 0.2
trainer:
  type: IndDATrainer
  args:
    epochs: 200
    save_dir: saved/
    save_period: 1
    verbosity: 2
    monitor: max val_accuracy_deg
    early_stop: 200
    tensorboard: true